"""Generate a hosts.toml from Better Agent Terminal's own profile store.

Reads ``profiles/index.json`` (host, port, pinned fingerprint). Tokens are NOT
copied: each host gets ``token_ref = "bat-profile:<id>"`` which is resolved at
connect time from BAT's ``remote-tokens.enc.json``.
"""

from __future__ import annotations

import json
import re
from pathlib import Path

from .config import DEFAULT_BAT_PROFILES_DIR, format_fingerprint, normalize_fingerprint
from .errors import ConfigError


def _toml_str(s: str) -> str:
    return json.dumps(s, ensure_ascii=False)


def _ws_url(host: str, port: int) -> str:
    h = f"[{host}]" if ":" in host else host
    return f"wss://{h}:{port}/"


def _safe_name(s: str) -> str:
    n = re.sub(r"[^A-Za-z0-9_.-]+", "-", s).strip("-.") or "host"
    return n[:64]


def read_bat_profiles(profiles_dir: str | Path = DEFAULT_BAT_PROFILES_DIR) -> list[dict]:
    pdir = Path(profiles_dir).expanduser()
    idx = pdir / "index.json"
    try:
        data = json.loads(idx.read_text())
    except (OSError, ValueError) as e:
        raise ConfigError(f"cannot read {idx}: {type(e).__name__}") from None
    out = []
    for p in data.get("profiles") or []:
        if p.get("type") != "remote":
            continue
        if not (p.get("remoteHost") and p.get("remotePort") and p.get("remoteFingerprint")):
            continue
        out.append(
            {
                "id": p["id"],
                "name": p.get("name") or p["id"],
                "host": p["remoteHost"],
                "port": int(p["remotePort"]),
                "fingerprint": normalize_fingerprint(p["remoteFingerprint"]),
                "remote_profile_id": p.get("remoteProfileId") or "default",
            }
        )
    return out


def render_hosts_toml(
    profiles: list[dict],
    *,
    profiles_dir: str = DEFAULT_BAT_PROFILES_DIR,
    rename: dict[str, str] | None = None,
    only: list[str] | None = None,
) -> str:
    rename = rename or {}
    lines = [
        "# Generated by `batc import-bat` from BAT's profiles/index.json.",
        "# Token values are NOT stored here: token_ref points at BAT's own token store.",
        "",
        "[client]",
        'label = "BAT Agent Connector"',
        "",
        "[safety]",
        "audit_preview_chars = 0",
        "write_min_interval_s = 60",
        "max_writes_per_hour = 30",
        "",
        "[bat]",
        f"profiles_dir = {_toml_str(profiles_dir)}",
        "",
    ]
    seen = set()
    for p in profiles:
        if only and p["id"] not in only:
            continue
        name = _safe_name(rename.get(p["id"], p["id"]))
        if name in seen:
            raise ConfigError(f"duplicate host name {name!r}; use --rename")
        seen.add(name)
        lines += [
            f"[hosts.{name}]",
            f"# BAT profile {_toml_str(p['name'])}",
            "url = " + _toml_str(_ws_url(p["host"], p["port"])),
            f"fingerprint = {_toml_str(format_fingerprint(p['fingerprint']))}",
            f"token_ref = {_toml_str('bat-profile:' + p['id'])}",
            f"profile_id = {_toml_str(p['remote_profile_id'])}",
            "writes = false",
            "",
        ]
    return "\n".join(lines)
